### ISSUE TITLE
Próxima reunión: 2019-06-19

### ISSUE THREAD

**Issue by miguelff** [remote-ast/about#2]
En esta issue se reflejan los puntos a tratar en la próxima reunión semanal 

### Puntos a tratar

* @mjsierra para investigar la forma de hacer el workshop remote friendly y poner una fecha. Miguel para ayudarla.
* @lmenezes  y @bertocq , preguntar si su mujer y hermano respectivamente quieren acercarse a la comunidad como trabajadores remotos que no pertenezcan al colectivo de programadores o diseñadores, ya que su input podría ser muy interesante.
* @miguelff  definir un formato muy poco restrictivo para que las calls sean productvas.
* Brainstorming sobre podríamos dar visibilidad (medios de comunicación? Universidades? Empresas?)
* Identidad gráfica: Qué pre-requisitos se necesitan? (planteado por @redhairgraphicworks)

### Referencias

* [Acta de la reunión anterior](../blob/master/log/2019-06-12.md)
* [Cómo conducir la reunión](../blob/master/docs/reuniones-semanales.md)

**Comment by redhairgraphicworks** [comment]
*

**Comment by redhairgraphicworks** [comment]
*

**Comment by miguelff** [comment]
Cerrada en favor de la siguiente reunión https://github.com/remote-ast/about/pull/4
